service: nhlbot
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-central-1
  environment:
    TELEGRAM_API_TOKEN: ${ssm:telegram_nhl_info_dev_bot_token}  

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  bot:
    handler: bin/bot
    events:
      - http:
          path: bot
          method: post
